language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
env:
  - REACT_APP_BACKEND_HOST=http://127.0.0.1:5000/api/v2
script:
  - npm test
  - npm run coverage
after_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
